
spring:
  # thymeleaf配置
  thymeleaf:
    # 关闭缓存
    cache: false
  # redis配置
  redis:
    # 主机IP
    host: localhost
    # 端口
    port: 6379
    # 默认数据库
    database: 0
    # 超时时间
    timeout: 6000ms
    lettuce:
      pool:
        # 最大连接数
        max-active: 8
        # 最大连接阻塞等待时间
        max-wait: 6000ms
        # 最大空闲连接
        max-idle: 10
        # 最小空闲连接
        min-idle: 1
  web:
    resources:
      cache:
        cachecontrol:
          max-age: 3600
      chain:
        # 资源链启用缓存
        cache: true
        # 启动资源链，默认禁用
        enabled: true
        # 启用压缩资源解析，默认禁用
        compressed: true
      add-mappings: true
      static-locations: classpath:/static/

# SQL打印
logging:
  level:
    cn.lysoy.seckill.mapper: debug

netty:
  #监听websocket连接的端口
  port: 9123
  #websocket连接地址  （此处要用电脑的ip,不然手机访问会出现问题）
  ws: ws://localhost:${netty.port}/ws


server:
  port: 8080
