spring:
  # thymeleaf配置
  thymeleaf:
    # 关闭缓存
    cache: false
  # redis配置
  redis:
    # 主机IP
    host: localhost
    # 端口
    port: 6379
    # 默认数据库
    database: 0
    # 超时时间
    timeout: 6000ms
    lettuce:
      pool:
        # 最大连接数
        max-active: 8
        # 最大连接阻塞等待时间
        max-wait: 6000ms
        # 最大空闲连接
        max-idle: 10
        # 最小空闲连接
        min-idle: 1
  # 数据源配置
  datasource:
    # Mysql8.X驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=UTF-8&serverTimeZone=Asia/Shanghai
    username: root
    password: root
    hikari:
      # 连接池名
      pool-name: Hikari
      # 最小空闲连接数
      minimum-idle: 6
      # 空闲连接存活最大时间（默认600000（10分钟））
      idle-timeout: 300000
      # 最大连接数（默认10）
      maximum-pool-size: 12
      # 从连接池返回的链接自动提交
      auto-commit: true
      # 最大存活时间，0表示永久存活
      max-lifetime: 1800000
      # 连接超时时间
      connection-timeout: 30000
      # 测试连接是否可用的查询语句
      connection-test-query: SELECT 1

# mybatis-plus配置
mybatis-plus:
  # Mapper.xml映射文件
  mapper-locations:
    - classpath*:/mapper/*Mapper.xml
  # Mybatis-plus数据返回类型别名
  type-aliases-package: cn.lysoy.seckill.pojo

# SQL打印
logging:
  level:
    cn.lysoy.seckill.mapper: debug
